//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        public EMPLEADOS()
        {
            this.BITACORA = new HashSet<BITACORA>();
            this.ESTADO_EVAL = new HashSet<ESTADO_EVAL>();
            this.OBJETIVO = new HashSet<OBJETIVO>();
        }
    
        public int No_Emp { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public string NombreCompleto { get; set; }
        public string Nivel4 { get; set; }
        public string Nivel6 { get; set; }
        public string Descripcion { get; set; }
        public string TipoEmpleado { get; set; }
        public string Activo { get; set; }
        public System.DateTime Fecha_Baja { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Departamento { get; set; }
        public string Jefe { get; set; }
        public string Area { get; set; }
        public string ID_Horario { get; set; }
        public string HORARIO { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Reminder { get; set; }
        public Nullable<int> id_Reminder { get; set; }
        public Nullable<System.DateTime> FechaReminder { get; set; }
        public string nombreUsuario { get; set; }
    
        public virtual ICollection<BITACORA> BITACORA { get; set; }
        public virtual ICollection<ESTADO_EVAL> ESTADO_EVAL { get; set; }
        public virtual ICollection<OBJETIVO> OBJETIVO { get; set; }
    }
}
