//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Evaluacion
    {
        public Re_Evaluacion()
        {
            this.COMPETENCIA = new HashSet<COMPETENCIA>();
        }
    
        public int ID_ReEvaluacion { get; set; }
        public Nullable<int> No_Emp { get; set; }
        public Nullable<System.DateTime> FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeTerminacion { get; set; }
        public string Estado { get; set; }
        public Nullable<double> CalificacionFinal { get; set; }
        public string ComentariosRh { get; set; }
        public string ComentariosPM { get; set; }
        public string TipoEvaluacion { get; set; }
        public string ComentariosGer { get; set; }
        public string EvaluadorRH { get; set; }
        public string EvaluadorPM { get; set; }
    
        public virtual ICollection<COMPETENCIA> COMPETENCIA { get; set; }
    }
}
