//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVE_DIRECTORY
    {
        public string userName { get; set; }
        public int userNumber { get; set; }
        public string userMail { get; set; }
        public Nullable<bool> Reminder { get; set; }
        public Nullable<int> id_Reminder { get; set; }
        public Nullable<System.DateTime> FechaReminder { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FRUpdate { get; set; }
        public Nullable<bool> RHPM { get; set; }
        public Nullable<System.DateTime> RecordatorioSemanal { get; set; }
        public Nullable<int> numberGerente { get; set; }
        public Nullable<System.DateTime> FObjetivo { get; set; }
        public Nullable<bool> Reminder2 { get; set; }
        public Nullable<int> id_Reminder2 { get; set; }
    }
}
