//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EvaluacionEntities : DbContext
    {
        public EvaluacionEntities()
            : base("name=EvaluacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<CALIFICACIONDERENDIMIENTO> CALIFICACIONDERENDIMIENTO { get; set; }
        public virtual DbSet<COMPETENCIA> COMPETENCIA { get; set; }
        public virtual DbSet<ESTADO_EVAL> ESTADO_EVAL { get; set; }
        public virtual DbSet<NOTIFICACION> NOTIFICACION { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<PLANTILLAEVALUACIONEXCEMPT> PLANTILLAEVALUACIONEXCEMPT { get; set; }
        public virtual DbSet<Re_Evaluacion> Re_Evaluacion { get; set; }
        public virtual DbSet<TIPODECOMPETENCIA> TIPODECOMPETENCIA { get; set; }
        public virtual DbSet<ACTIVE_DIRECTORY> ACTIVE_DIRECTORY { get; set; }
        public virtual DbSet<REMINDERS> REMINDERS { get; set; }
        public virtual DbSet<Emp> Emp { get; set; }
        public virtual DbSet<Objetivo1> Objetivo1Set { get; set; }
        public virtual DbSet<PeriodoObjetivo> PeriodoObjetivo { get; set; }
        public virtual DbSet<Re_Objetivo> Re_Objetivo { get; set; }
        public virtual DbSet<CategoriaObjetivos> CategoriaObjetivos { get; set; }
        public virtual DbSet<TiposObjetivos> TiposObjetivos { get; set; }
    
        public virtual int sp_Actualiza_EstadoReminder(Nullable<int> noEmpleado)
        {
            var noEmpleadoParameter = noEmpleado.HasValue ?
                new ObjectParameter("noEmpleado", noEmpleado) :
                new ObjectParameter("noEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualiza_EstadoReminder", noEmpleadoParameter);
        }
    
        public virtual int sp_Actualiza_EstadoSemanal(Nullable<int> noEmpleado)
        {
            var noEmpleadoParameter = noEmpleado.HasValue ?
                new ObjectParameter("noEmpleado", noEmpleado) :
                new ObjectParameter("noEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualiza_EstadoSemanal", noEmpleadoParameter);
        }
    
        public virtual ObjectResult<string> sp_CargaDepartamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_CargaDepartamentos");
        }
    
        public virtual ObjectResult<sp_CargaEmpleados_Result> sp_CargaEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargaEmpleados_Result>("sp_CargaEmpleados");
        }
    
        public virtual ObjectResult<sp_CargaEmpleadosReporte_Result> sp_CargaEmpleadosReporte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargaEmpleadosReporte_Result>("sp_CargaEmpleadosReporte");
        }
    
        public virtual ObjectResult<string> sp_CargaJefes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_CargaJefes");
        }
    
        public virtual ObjectResult<sp_CargarCompetenciasGuardadas_Result> sp_CargarCompetenciasGuardadas(string tipoDeCompetencia, Nullable<int> numEmp, Nullable<int> iDPeriodo, Nullable<int> iDeva)
        {
            var tipoDeCompetenciaParameter = tipoDeCompetencia != null ?
                new ObjectParameter("TipoDeCompetencia", tipoDeCompetencia) :
                new ObjectParameter("TipoDeCompetencia", typeof(string));
    
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var iDevaParameter = iDeva.HasValue ?
                new ObjectParameter("IDeva", iDeva) :
                new ObjectParameter("IDeva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargarCompetenciasGuardadas_Result>("sp_CargarCompetenciasGuardadas", tipoDeCompetenciaParameter, numEmpParameter, iDPeriodoParameter, iDevaParameter);
        }
    
        public virtual ObjectResult<sp_CargarDatosReporte_Result> sp_CargarDatosReporte(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargarDatosReporte_Result>("sp_CargarDatosReporte", numEmpParameter);
        }
    
        public virtual ObjectResult<sp_CargarEmpleadoPrueba_Result> sp_CargarEmpleadoPrueba(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargarEmpleadoPrueba_Result>("sp_CargarEmpleadoPrueba", numEmpParameter);
        }
    
        public virtual ObjectResult<sp_CargarPlantilla_Result> sp_CargarPlantilla(Nullable<int> numEmp, string tipoDeCompetencia)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            var tipoDeCompetenciaParameter = tipoDeCompetencia != null ?
                new ObjectParameter("TipoDeCompetencia", tipoDeCompetencia) :
                new ObjectParameter("TipoDeCompetencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargarPlantilla_Result>("sp_CargarPlantilla", numEmpParameter, tipoDeCompetenciaParameter);
        }
    
        public virtual ObjectResult<sp_CargarReporte_Result> sp_CargarReporte(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargarReporte_Result>("sp_CargarReporte", numEmpParameter);
        }
    
        public virtual ObjectResult<string> sp_CargaTipos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_CargaTipos");
        }
    
        public virtual int sp_CrearNuevoObjetivo(Nullable<int> iDObj, Nullable<int> numeroEmpleado, string descripcion, Nullable<int> valor, string tipo, Nullable<int> iDPeriodo, Nullable<int> categoria, string periodoObj)
        {
            var iDObjParameter = iDObj.HasValue ?
                new ObjectParameter("IDObj", iDObj) :
                new ObjectParameter("IDObj", typeof(int));
    
            var numeroEmpleadoParameter = numeroEmpleado.HasValue ?
                new ObjectParameter("NumeroEmpleado", numeroEmpleado) :
                new ObjectParameter("NumeroEmpleado", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("Valor", valor) :
                new ObjectParameter("Valor", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("Categoria", categoria) :
                new ObjectParameter("Categoria", typeof(int));
    
            var periodoObjParameter = periodoObj != null ?
                new ObjectParameter("PeriodoObj", periodoObj) :
                new ObjectParameter("PeriodoObj", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearNuevoObjetivo", iDObjParameter, numeroEmpleadoParameter, descripcionParameter, valorParameter, tipoParameter, iDPeriodoParameter, categoriaParameter, periodoObjParameter);
        }
    
        public virtual int sp_CrearPeriodo(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal, string descripcion)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearPeriodo", fechaInicioParameter, fechaFinalParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<string> sp_DeterminarTipoEmpleado(Nullable<int> no_Emp)
        {
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DeterminarTipoEmpleado", no_EmpParameter);
        }
    
        public virtual int sp_EditarObjetivo(Nullable<int> iDObjetivo, Nullable<int> numeroDeEmpleado, string descripcion, Nullable<int> peso, string tipo, Nullable<int> iDPeriodo, Nullable<int> pesoAnt, string descAnt, Nullable<int> categoria, Nullable<int> periodoObj)
        {
            var iDObjetivoParameter = iDObjetivo.HasValue ?
                new ObjectParameter("IDObjetivo", iDObjetivo) :
                new ObjectParameter("IDObjetivo", typeof(int));
    
            var numeroDeEmpleadoParameter = numeroDeEmpleado.HasValue ?
                new ObjectParameter("NumeroDeEmpleado", numeroDeEmpleado) :
                new ObjectParameter("NumeroDeEmpleado", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var pesoAntParameter = pesoAnt.HasValue ?
                new ObjectParameter("PesoAnt", pesoAnt) :
                new ObjectParameter("PesoAnt", typeof(int));
    
            var descAntParameter = descAnt != null ?
                new ObjectParameter("DescAnt", descAnt) :
                new ObjectParameter("DescAnt", typeof(string));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("Categoria", categoria) :
                new ObjectParameter("Categoria", typeof(int));
    
            var periodoObjParameter = periodoObj.HasValue ?
                new ObjectParameter("PeriodoObj", periodoObj) :
                new ObjectParameter("PeriodoObj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarObjetivo", iDObjetivoParameter, numeroDeEmpleadoParameter, descripcionParameter, pesoParameter, tipoParameter, iDPeriodoParameter, pesoAntParameter, descAntParameter, categoriaParameter, periodoObjParameter);
        }
    
        public virtual int sp_EliminarMiObjetivo(Nullable<int> numEmp, string descObjetivo, Nullable<int> intPeso, Nullable<int> periodo)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            var descObjetivoParameter = descObjetivo != null ?
                new ObjectParameter("DescObjetivo", descObjetivo) :
                new ObjectParameter("DescObjetivo", typeof(string));
    
            var intPesoParameter = intPeso.HasValue ?
                new ObjectParameter("intPeso", intPeso) :
                new ObjectParameter("intPeso", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarMiObjetivo", numEmpParameter, descObjetivoParameter, intPesoParameter, periodoParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_EstatusTotalEvaluacion(Nullable<int> numEmp, Nullable<int> iDPeriodo, Nullable<int> idEvaluacion)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var idEvaluacionParameter = idEvaluacion.HasValue ?
                new ObjectParameter("idEvaluacion", idEvaluacion) :
                new ObjectParameter("idEvaluacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_EstatusTotalEvaluacion", numEmpParameter, iDPeriodoParameter, idEvaluacionParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_EstatusTotalEvaluacionJefe(Nullable<int> numEmp, Nullable<int> iDPeriodo, Nullable<int> idReEvaluacion2)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var idReEvaluacion2Parameter = idReEvaluacion2.HasValue ?
                new ObjectParameter("idReEvaluacion2", idReEvaluacion2) :
                new ObjectParameter("idReEvaluacion2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_EstatusTotalEvaluacionJefe", numEmpParameter, iDPeriodoParameter, idReEvaluacion2Parameter);
        }
    
        public virtual ObjectResult<string> sp_EvaluarObjetivo(Nullable<int> iDObjetivo, Nullable<int> numeroEmpleado, Nullable<int> iDPeriodo, string comentarios, Nullable<double> calificacion)
        {
            var iDObjetivoParameter = iDObjetivo.HasValue ?
                new ObjectParameter("IDObjetivo", iDObjetivo) :
                new ObjectParameter("IDObjetivo", typeof(int));
    
            var numeroEmpleadoParameter = numeroEmpleado.HasValue ?
                new ObjectParameter("NumeroEmpleado", numeroEmpleado) :
                new ObjectParameter("NumeroEmpleado", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("Calificacion", calificacion) :
                new ObjectParameter("Calificacion", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_EvaluarObjetivo", iDObjetivoParameter, numeroEmpleadoParameter, iDPeriodoParameter, comentariosParameter, calificacionParameter);
        }
    
        public virtual int sp_EvImpresa(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EvImpresa", numeroParameter);
        }
    
        public virtual int sp_FinalizaPM(Nullable<int> numero, Nullable<int> idEv)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            var idEvParameter = idEv.HasValue ?
                new ObjectParameter("idEv", idEv) :
                new ObjectParameter("idEv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FinalizaPM", numeroParameter, idEvParameter);
        }
    
        public virtual int sp_FinEvaluacion(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FinEvaluacion", numeroParameter);
        }
    
        public virtual int sp_GuardarEstadoDeCompetencia(Nullable<int> iDCompetencia, Nullable<int> noEmp, Nullable<int> periodo, string comentarios, string calificacionDeRendimiento, string userName, Nullable<int> iDReEvaluacion)
        {
            var iDCompetenciaParameter = iDCompetencia.HasValue ?
                new ObjectParameter("IDCompetencia", iDCompetencia) :
                new ObjectParameter("IDCompetencia", typeof(int));
    
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var calificacionDeRendimientoParameter = calificacionDeRendimiento != null ?
                new ObjectParameter("CalificacionDeRendimiento", calificacionDeRendimiento) :
                new ObjectParameter("CalificacionDeRendimiento", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var iDReEvaluacionParameter = iDReEvaluacion.HasValue ?
                new ObjectParameter("IDReEvaluacion", iDReEvaluacion) :
                new ObjectParameter("IDReEvaluacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuardarEstadoDeCompetencia", iDCompetenciaParameter, noEmpParameter, periodoParameter, comentariosParameter, calificacionDeRendimientoParameter, userNameParameter, iDReEvaluacionParameter);
        }
    
        public virtual int sp_GuardarYTerminarEvaluacion(Nullable<int> no_Emp, Nullable<int> iDPeriodo, Nullable<int> no_Evaluador, string comentarios, Nullable<int> idReEvaluacion)
        {
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var no_EvaluadorParameter = no_Evaluador.HasValue ?
                new ObjectParameter("No_Evaluador", no_Evaluador) :
                new ObjectParameter("No_Evaluador", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("comentarios", comentarios) :
                new ObjectParameter("comentarios", typeof(string));
    
            var idReEvaluacionParameter = idReEvaluacion.HasValue ?
                new ObjectParameter("idReEvaluacion", idReEvaluacion) :
                new ObjectParameter("idReEvaluacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuardarYTerminarEvaluacion", no_EmpParameter, iDPeriodoParameter, no_EvaluadorParameter, comentariosParameter, idReEvaluacionParameter);
        }
    
        public virtual ObjectResult<sp_ListarPendienteDeObjetivos_Result> sp_ListarPendienteDeObjetivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPendienteDeObjetivos_Result>("sp_ListarPendienteDeObjetivos");
        }
    
        public virtual ObjectResult<sp_ListaSendReminders_Result> sp_ListaSendReminders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaSendReminders_Result>("sp_ListaSendReminders");
        }
    
        public virtual int sp_LoadReminders(string valorCorto, Nullable<int> numEmp)
        {
            var valorCortoParameter = valorCorto != null ?
                new ObjectParameter("valorCorto", valorCorto) :
                new ObjectParameter("valorCorto", typeof(string));
    
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("numEmp", numEmp) :
                new ObjectParameter("numEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LoadReminders", valorCortoParameter, numEmpParameter);
        }
    
        public virtual int sp_MarcarNotificacionComoLeida(Nullable<int> no_Emp, Nullable<int> iD_Notificacion)
        {
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            var iD_NotificacionParameter = iD_Notificacion.HasValue ?
                new ObjectParameter("ID_Notificacion", iD_Notificacion) :
                new ObjectParameter("ID_Notificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MarcarNotificacionComoLeida", no_EmpParameter, iD_NotificacionParameter);
        }
    
        public virtual ObjectResult<sp_misEmpleadosConEvaluacionPendiente_Result> sp_misEmpleadosConEvaluacionPendiente(string primerNombre, string primerApellido)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_misEmpleadosConEvaluacionPendiente_Result>("sp_misEmpleadosConEvaluacionPendiente", primerNombreParameter, primerApellidoParameter);
        }
    
        public virtual ObjectResult<sp_misEmpleadosSinCorreo_Result> sp_misEmpleadosSinCorreo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_misEmpleadosSinCorreo_Result>("sp_misEmpleadosSinCorreo");
        }
    
        public virtual ObjectResult<sp_MisNotificaciones_Result> sp_MisNotificaciones(Nullable<int> numEmpleado, Nullable<int> iDPeriodo)
        {
            var numEmpleadoParameter = numEmpleado.HasValue ?
                new ObjectParameter("NumEmpleado", numEmpleado) :
                new ObjectParameter("NumEmpleado", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MisNotificaciones_Result>("sp_MisNotificaciones", numEmpleadoParameter, iDPeriodoParameter);
        }
    
        public virtual ObjectResult<sp_MisObjetivos_Result> sp_MisObjetivos(Nullable<int> numeroDeEmpleado, Nullable<int> periodo)
        {
            var numeroDeEmpleadoParameter = numeroDeEmpleado.HasValue ?
                new ObjectParameter("NumeroDeEmpleado", numeroDeEmpleado) :
                new ObjectParameter("NumeroDeEmpleado", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MisObjetivos_Result>("sp_MisObjetivos", numeroDeEmpleadoParameter, periodoParameter);
        }
    
        public virtual ObjectResult<sp_MisObjetivosRealizados_Result> sp_MisObjetivosRealizados(Nullable<int> numeroDeEmpleado, Nullable<int> periodo)
        {
            var numeroDeEmpleadoParameter = numeroDeEmpleado.HasValue ?
                new ObjectParameter("NumeroDeEmpleado", numeroDeEmpleado) :
                new ObjectParameter("NumeroDeEmpleado", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MisObjetivosRealizados_Result>("sp_MisObjetivosRealizados", numeroDeEmpleadoParameter, periodoParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerCompetencia_Result> sp_ObtenerCompetencia(string tipoDeCompetencia)
        {
            var tipoDeCompetenciaParameter = tipoDeCompetencia != null ?
                new ObjectParameter("TipoDeCompetencia", tipoDeCompetencia) :
                new ObjectParameter("TipoDeCompetencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerCompetencia_Result>("sp_ObtenerCompetencia", tipoDeCompetenciaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ObtenerUltimoPeriodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ObtenerUltimoPeriodo");
        }
    
        public virtual ObjectResult<sp_PendientesDeAprobacion_Result> sp_PendientesDeAprobacion(Nullable<int> no_Emp)
        {
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PendientesDeAprobacion_Result>("sp_PendientesDeAprobacion", no_EmpParameter);
        }
    
        public virtual int sp_RechazaPM(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RechazaPM", numeroParameter);
        }
    
        public virtual int sp_rechazaRecursos(Nullable<int> no_Emp, string comentario)
        {
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rechazaRecursos", no_EmpParameter, comentarioParameter);
        }
    
        public virtual int sp_RechazaRH(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RechazaRH", numeroParameter);
        }
    
        public virtual int sp_regresaEvPM(Nullable<int> no_Emp, string comentario)
        {
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_regresaEvPM", no_EmpParameter, comentarioParameter);
        }
    
        public virtual int sp_TerminarDeFormularObjetivos(Nullable<int> numeroEmpleado, Nullable<int> iDPeriodo)
        {
            var numeroEmpleadoParameter = numeroEmpleado.HasValue ?
                new ObjectParameter("NumeroEmpleado", numeroEmpleado) :
                new ObjectParameter("NumeroEmpleado", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TerminarDeFormularObjetivos", numeroEmpleadoParameter, iDPeriodoParameter);
        }
    
        public virtual int sp_validaRecursos(Nullable<int> no_Emp, string comentario)
        {
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_validaRecursos", no_EmpParameter, comentarioParameter);
        }
    
        public virtual ObjectResult<string> sp_ValidarEvaluacionExistente(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ValidarEvaluacionExistente", numEmpParameter);
        }
    
        public virtual ObjectResult<sp_ValidarNombreDeUsuario_Result> sp_ValidarNombreDeUsuario(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ValidarNombreDeUsuario_Result>("sp_ValidarNombreDeUsuario", userParameter);
        }
    
        public virtual ObjectResult<string> sp_ValidarUsuario(string nombreUsuarioActiveD)
        {
            var nombreUsuarioActiveDParameter = nombreUsuarioActiveD != null ?
                new ObjectParameter("NombreUsuarioActiveD", nombreUsuarioActiveD) :
                new ObjectParameter("NombreUsuarioActiveD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ValidarUsuario", nombreUsuarioActiveDParameter);
        }
    
        public virtual ObjectResult<string> traeEmail(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("traeEmail", userParameter);
        }
    
        public virtual int validaReminderEnviar(Nullable<int> number)
        {
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("validaReminderEnviar", numberParameter);
        }
    
        public virtual ObjectResult<verificaSemana_Result> verificaSemana()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verificaSemana_Result>("verificaSemana");
        }
    
        public virtual int sp_ApruebaPM(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ApruebaPM", numeroParameter);
        }
    
        public virtual int sp_ApruebaRH(Nullable<int> numero, Nullable<int> idEvaluacion)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            var idEvaluacionParameter = idEvaluacion.HasValue ?
                new ObjectParameter("idEvaluacion", idEvaluacion) :
                new ObjectParameter("idEvaluacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ApruebaRH", numeroParameter, idEvaluacionParameter);
        }
    
        public virtual ObjectResult<string> sp_Carga_ValorReminders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Carga_ValorReminders");
        }
    
        public virtual int sp_AsignarCorreoEmpleado(string nombreUsuario, Nullable<int> no_Emp, string correo)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var no_EmpParameter = no_Emp.HasValue ?
                new ObjectParameter("No_Emp", no_Emp) :
                new ObjectParameter("No_Emp", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AsignarCorreoEmpleado", nombreUsuarioParameter, no_EmpParameter, correoParameter);
        }
    
        public virtual int sp_ActualizarEmpleadosAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarEmpleadosAD");
        }
    
        public virtual int sp_AprobarEv(Nullable<int> noEmp, string comentarios, string tipoEmpleado, Nullable<int> idEv)
        {
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var tipoEmpleadoParameter = tipoEmpleado != null ?
                new ObjectParameter("TipoEmpleado", tipoEmpleado) :
                new ObjectParameter("TipoEmpleado", typeof(string));
    
            var idEvParameter = idEv.HasValue ?
                new ObjectParameter("idEv", idEv) :
                new ObjectParameter("idEv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AprobarEv", noEmpParameter, comentariosParameter, tipoEmpleadoParameter, idEvParameter);
        }
    
        public virtual int sp_RetroalimentarEv(Nullable<int> noEmp, string comentarios, string tipoEmpleado, string evaluador, Nullable<int> idEvaluacion)
        {
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var tipoEmpleadoParameter = tipoEmpleado != null ?
                new ObjectParameter("TipoEmpleado", tipoEmpleado) :
                new ObjectParameter("TipoEmpleado", typeof(string));
    
            var evaluadorParameter = evaluador != null ?
                new ObjectParameter("Evaluador", evaluador) :
                new ObjectParameter("Evaluador", typeof(string));
    
            var idEvaluacionParameter = idEvaluacion.HasValue ?
                new ObjectParameter("idEvaluacion", idEvaluacion) :
                new ObjectParameter("idEvaluacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetroalimentarEv", noEmpParameter, comentariosParameter, tipoEmpleadoParameter, evaluadorParameter, idEvaluacionParameter);
        }
    
        public virtual ObjectResult<sp_CargarComentariosReporte_Result> sp_CargarComentariosReporte(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargarComentariosReporte_Result>("sp_CargarComentariosReporte", numEmpParameter);
        }
    
        public virtual ObjectResult<sp_EstatusEvaluaciones_Result> sp_EstatusEvaluaciones(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EstatusEvaluaciones_Result>("sp_EstatusEvaluaciones", numeroParameter);
        }
    
        public virtual ObjectResult<string> sp_GetTipoEmpleado(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetTipoEmpleado", numEmpParameter);
        }
    
        public virtual ObjectResult<sp_MiEvaluacion_Result> sp_MiEvaluacion(Nullable<int> noEmp)
        {
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MiEvaluacion_Result>("sp_MiEvaluacion", noEmpParameter);
        }
    
        public virtual ObjectResult<sp_misEmpleadosConEvaluacionEnEspera_Result> sp_misEmpleadosConEvaluacionEnEspera(string primerNombre, string primerApellido)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_misEmpleadosConEvaluacionEnEspera_Result>("sp_misEmpleadosConEvaluacionEnEspera", primerNombreParameter, primerApellidoParameter);
        }
    
        public virtual ObjectResult<sp_misEmpleadosConEvaluacionTerminada_Result> sp_misEmpleadosConEvaluacionTerminada(string primerNombre, string primerApellido)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_misEmpleadosConEvaluacionTerminada_Result>("sp_misEmpleadosConEvaluacionTerminada", primerNombreParameter, primerApellidoParameter);
        }
    
        public virtual ObjectResult<sp_ListarCursosAsistidos_Result> sp_ListarCursosAsistidos(Nullable<int> noEmp)
        {
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCursosAsistidos_Result>("sp_ListarCursosAsistidos", noEmpParameter);
        }
    
        public virtual ObjectResult<EstatusEvaluacionesTerminadas_Result> EstatusEvaluacionesTerminadas(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstatusEvaluacionesTerminadas_Result>("EstatusEvaluacionesTerminadas", numeroParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Bnivel(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Bnivel", numeroParameter);
        }
    
        public virtual ObjectResult<sp_EstatusObjetivos_Result> sp_EstatusObjetivos(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("numEmp", numEmp) :
                new ObjectParameter("numEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EstatusObjetivos_Result>("sp_EstatusObjetivos", numEmpParameter);
        }
    
        public virtual int sp_FinalizaObjetivo(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FinalizaObjetivo", numeroParameter);
        }
    
        public virtual int sp_GuardarEstadoDeObjetivo(Nullable<int> iDObjetivo, Nullable<int> noEmp, Nullable<int> periodo, string comentarios, Nullable<int> iDReEvaluacion, Nullable<int> avance)
        {
            var iDObjetivoParameter = iDObjetivo.HasValue ?
                new ObjectParameter("IDObjetivo", iDObjetivo) :
                new ObjectParameter("IDObjetivo", typeof(int));
    
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var iDReEvaluacionParameter = iDReEvaluacion.HasValue ?
                new ObjectParameter("IDReEvaluacion", iDReEvaluacion) :
                new ObjectParameter("IDReEvaluacion", typeof(int));
    
            var avanceParameter = avance.HasValue ?
                new ObjectParameter("Avance", avance) :
                new ObjectParameter("Avance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuardarEstadoDeObjetivo", iDObjetivoParameter, noEmpParameter, periodoParameter, comentariosParameter, iDReEvaluacionParameter, avanceParameter);
        }
    
        public virtual ObjectResult<string> sp_ValidaObjetivoActual(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("numEmp", numEmp) :
                new ObjectParameter("numEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ValidaObjetivoActual", numEmpParameter);
        }
    
        public virtual ObjectResult<string> sp_ValidarObjetivosExistente(Nullable<int> numEmp)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ValidarObjetivosExistente", numEmpParameter);
        }
    
        public virtual ObjectResult<sp_CargaEmpleadosSalary_Result> sp_CargaEmpleadosSalary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargaEmpleadosSalary_Result>("sp_CargaEmpleadosSalary");
        }
    
        public virtual int sp_LoadObjetivos(string valorCorto, Nullable<int> numEmp, string periodo)
        {
            var valorCortoParameter = valorCorto != null ?
                new ObjectParameter("valorCorto", valorCorto) :
                new ObjectParameter("valorCorto", typeof(string));
    
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("numEmp", numEmp) :
                new ObjectParameter("numEmp", typeof(int));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LoadObjetivos", valorCortoParameter, numEmpParameter, periodoParameter);
        }
    
        public virtual ObjectResult<sp_RevisionObjetivosTerminados_Result> sp_RevisionObjetivosTerminados(Nullable<int> numEmp, Nullable<int> periodo)
        {
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RevisionObjetivosTerminados_Result>("sp_RevisionObjetivosTerminados", numEmpParameter, periodoParameter);
        }
    
        public virtual ObjectResult<sp_misEmpleadosConObjetivosPendientes_Result> sp_misEmpleadosConObjetivosPendientes(string primerNombre, string primerApellido)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_misEmpleadosConObjetivosPendientes_Result>("sp_misEmpleadosConObjetivosPendientes", primerNombreParameter, primerApellidoParameter);
        }
    
        public virtual int sp_GuardarYTerminarObjetivos(Nullable<int> iDReObjetivo, Nullable<int> noEmp, Nullable<int> iDPeriodo, string revisionActual)
        {
            var iDReObjetivoParameter = iDReObjetivo.HasValue ?
                new ObjectParameter("IDReObjetivo", iDReObjetivo) :
                new ObjectParameter("IDReObjetivo", typeof(int));
    
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var iDPeriodoParameter = iDPeriodo.HasValue ?
                new ObjectParameter("IDPeriodo", iDPeriodo) :
                new ObjectParameter("IDPeriodo", typeof(int));
    
            var revisionActualParameter = revisionActual != null ?
                new ObjectParameter("RevisionActual", revisionActual) :
                new ObjectParameter("RevisionActual", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuardarYTerminarObjetivos", iDReObjetivoParameter, noEmpParameter, iDPeriodoParameter, revisionActualParameter);
        }
    
        public virtual int sp_AprobarObj(Nullable<int> noEmp, string comentario)
        {
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AprobarObj", noEmpParameter, comentarioParameter);
        }
    
        public virtual int sp_RechazaObjetivos(Nullable<int> numero)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RechazaObjetivos", numeroParameter);
        }
    
        public virtual int sp_RechazarObjetivo(Nullable<int> noEmp, string comentarios)
        {
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RechazarObjetivo", noEmpParameter, comentariosParameter);
        }
    
        public virtual ObjectResult<sp_getPeriodos_Result> sp_getPeriodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getPeriodos_Result>("sp_getPeriodos");
        }
    
        public virtual int sp_setPeriodos(string q1, string q2, string q3, string q4, string nombre)
        {
            var q1Parameter = q1 != null ?
                new ObjectParameter("Q1", q1) :
                new ObjectParameter("Q1", typeof(string));
    
            var q2Parameter = q2 != null ?
                new ObjectParameter("Q2", q2) :
                new ObjectParameter("Q2", typeof(string));
    
            var q3Parameter = q3 != null ?
                new ObjectParameter("Q3", q3) :
                new ObjectParameter("Q3", typeof(string));
    
            var q4Parameter = q4 != null ?
                new ObjectParameter("Q4", q4) :
                new ObjectParameter("Q4", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_setPeriodos", q1Parameter, q2Parameter, q3Parameter, q4Parameter, nombreParameter);
        }
    
        public virtual int sp_ActualizaMeta(string meta, Nullable<int> numEmp)
        {
            var metaParameter = meta != null ?
                new ObjectParameter("meta", meta) :
                new ObjectParameter("meta", typeof(string));
    
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("numEmp", numEmp) :
                new ObjectParameter("numEmp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaMeta", metaParameter, numEmpParameter);
        }
    
        public virtual int sp_GuardarEstadoDeObjetivoOnGoing(Nullable<int> iDObjetivo, Nullable<int> noEmp, Nullable<int> periodo, string comentarios, Nullable<int> iDReEvaluacion, Nullable<int> avance, string cuarto)
        {
            var iDObjetivoParameter = iDObjetivo.HasValue ?
                new ObjectParameter("IDObjetivo", iDObjetivo) :
                new ObjectParameter("IDObjetivo", typeof(int));
    
            var noEmpParameter = noEmp.HasValue ?
                new ObjectParameter("NoEmp", noEmp) :
                new ObjectParameter("NoEmp", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var iDReEvaluacionParameter = iDReEvaluacion.HasValue ?
                new ObjectParameter("IDReEvaluacion", iDReEvaluacion) :
                new ObjectParameter("IDReEvaluacion", typeof(int));
    
            var avanceParameter = avance.HasValue ?
                new ObjectParameter("Avance", avance) :
                new ObjectParameter("Avance", typeof(int));
    
            var cuartoParameter = cuarto != null ?
                new ObjectParameter("cuarto", cuarto) :
                new ObjectParameter("cuarto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuardarEstadoDeObjetivoOnGoing", iDObjetivoParameter, noEmpParameter, periodoParameter, comentariosParameter, iDReEvaluacionParameter, avanceParameter, cuartoParameter);
        }
    
        public virtual ObjectResult<sp_MisObjetivosXD_Result> sp_MisObjetivosXD(Nullable<int> numeroDeEmpleado, Nullable<int> periodo)
        {
            var numeroDeEmpleadoParameter = numeroDeEmpleado.HasValue ?
                new ObjectParameter("NumeroDeEmpleado", numeroDeEmpleado) :
                new ObjectParameter("NumeroDeEmpleado", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MisObjetivosXD_Result>("sp_MisObjetivosXD", numeroDeEmpleadoParameter, periodoParameter);
        }
    
        public virtual int sp_ActualizaMetaEdit(string meta, Nullable<int> numEmp, Nullable<int> idObjetivo)
        {
            var metaParameter = meta != null ?
                new ObjectParameter("meta", meta) :
                new ObjectParameter("meta", typeof(string));
    
            var numEmpParameter = numEmp.HasValue ?
                new ObjectParameter("numEmp", numEmp) :
                new ObjectParameter("numEmp", typeof(int));
    
            var idObjetivoParameter = idObjetivo.HasValue ?
                new ObjectParameter("idObjetivo", idObjetivo) :
                new ObjectParameter("idObjetivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaMetaEdit", metaParameter, numEmpParameter, idObjetivoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> yearFiscal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("yearFiscal");
        }
    
        public virtual ObjectResult<sp_CargaEmpleadosReportePP_Result> sp_CargaEmpleadosReportePP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargaEmpleadosReportePP_Result>("sp_CargaEmpleadosReportePP");
        }
    }
}
