//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaObjetivos
    {
        public CategoriaObjetivos()
        {
            this.Objetivo = new HashSet<Objetivo1>();
        }
    
        public int ID_CategoriaObjetivos { get; set; }
        public string Valor { get; set; }
        public string Definicion { get; set; }
    
        public virtual ICollection<Objetivo1> Objetivo { get; set; }
    }
}
