//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo1
    {
        public int ID_Objetivo { get; set; }
        public int ID_ReObjetivo { get; set; }
        public int ID_CategoriaObjetivos { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Peso { get; set; }
        public string Tipo { get; set; }
        public string ComentariosJefe { get; set; }
        public Nullable<int> Avance { get; set; }
        public string TipObj { get; set; }
        public Nullable<int> TipoObjNum { get; set; }
        public string Meta { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
    
        public virtual Re_Objetivo Re_Objetivo { get; set; }
        public virtual CategoriaObjetivos CategoriaObjetivos { get; set; }
    }
}
