//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODO
    {
        public PERIODO()
        {
            this.BITACORA = new HashSet<BITACORA>();
            this.COMPETENCIA = new HashSet<COMPETENCIA>();
            this.PeriodoObjetivo = new HashSet<PeriodoObjetivo>();
            this.Re_Objetivo = new HashSet<Re_Objetivo>();
        }
    
        public int ID_Periodo { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Final { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<BITACORA> BITACORA { get; set; }
        public virtual ICollection<COMPETENCIA> COMPETENCIA { get; set; }
        public virtual ICollection<PeriodoObjetivo> PeriodoObjetivo { get; set; }
        public virtual ICollection<Re_Objetivo> Re_Objetivo { get; set; }
    }
}
