//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoObjetivo
    {
        public int ID_PeriodoObjetivo { get; set; }
        public int ID_Periodo { get; set; }
        public string Periodo { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
    
        public virtual PERIODO PERIODO1 { get; set; }
    }
}
