//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Objetivo
    {
        public Re_Objetivo()
        {
            this.Objetivo = new HashSet<Objetivo1>();
        }
    
        public int ID_ReObjetivo { get; set; }
        public int ID_Periodo { get; set; }
        public int No_Emp { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTerminacion { get; set; }
        public string Estado { get; set; }
        public string Comentario { get; set; }
        public Nullable<double> CalificacionFinal { get; set; }
        public string ComentarioFinal { get; set; }
        public string PeriodoActual { get; set; }
    
        public virtual ICollection<Objetivo1> Objetivo { get; set; }
        public virtual PERIODO PERIODO { get; set; }
    }
}
