//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    
    public partial class sp_ValidarNombreDeUsuario_Result1
    {
        public int No_Emp { get; set; }
        public string userName { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string TipoEmpleado { get; set; }
        public string JEFE { get; set; }
        public string NombreAD { get; set; }
        public string ApellidoAD { get; set; }
    }
}
