//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public int ID_LOG { get; set; }
        public int ID_Periodo { get; set; }
        public int No_Emp { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual PERIODO PERIODO { get; set; }
    }
}
