//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLAEVALUACIONEXCEMPT
    {
        public PLANTILLAEVALUACIONEXCEMPT()
        {
            this.COMPETENCIA = new HashSet<COMPETENCIA>();
        }
    
        public int ID_PlantillaEvaluacionExcempt { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Contenido { get; set; }
        public Nullable<int> ID_TipoDeCompetencia { get; set; }
        public Nullable<short> OrdenPlantilla { get; set; }
    
        public virtual ICollection<COMPETENCIA> COMPETENCIA { get; set; }
        public virtual TIPODECOMPETENCIA TIPODECOMPETENCIA { get; set; }
    }
}
