//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    
    public partial class sp_MisNotificaciones_Result1
    {
        public int ID_Notificacion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int No_Empleado { get; set; }
        public int ID_Periodo { get; set; }
        public Nullable<System.TimeSpan> MomentoDeNotificacion { get; set; }
        public Nullable<int> EstadoDeNotificacion { get; set; }
    }
}
