//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvaluacionDesempeno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUACIONOBJETIVO
    {
        public int ID_EvalObj { get; set; }
        public int ID_Objetivo { get; set; }
        public string Comentarios { get; set; }
        public double Calificacion { get; set; }
    
        public virtual OBJETIVO OBJETIVO { get; set; }
    }
}
